name: "Build and Publish Releases"
on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v6
        with:
          ref: main
      - name: Login to Github Container Registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and publish image
        run: |
          /bin/bash build.sh push
